# Generated by Django 3.1.7 on 2021-02-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('text_field', models.TextField(blank=True, null=True)),
                ('article_image', models.ImageField(upload_to='media')),
            ],
        ),
    ]
