# Generated by Django 3.0.5 on 2021-03-01 18:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0011_auto_20210301_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='clicked_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='article',
            name='clicks',
        ),
        migrations.AddField(
            model_name='article',
            name='clicks',
            field=models.PositiveIntegerField(default=0, verbose_name='Views'),
        ),
    ]
