# Generated by Django 3.0.5 on 2021-03-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_newsletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='text_field',
        ),
        migrations.AddField(
            model_name='article',
            name='text',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
