# Generated by Django 3.0.5 on 2021-03-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210305_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='text_field',
            field=models.TextField(blank=True, null=True),
        ),
    ]
