# Generated by Django 3.0.5 on 2021-03-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_article_text_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
