# Generated by Django 3.0.5 on 2021-03-06 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210305_2346'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
